### PR TITLE
Fix #59, add fields to optimized_bn128.__init__

### LINKED ISSUE #59: py-evm tests will fail with current master branch of py_ecc
* py-evm Version: master branch at d6adf9039647b6fc39b9d79725e9331008a5c438
* OS: osx
* Python Version (python --version): Python 3.7.0
* Environment (output of `pip freeze`):

### What is wrong?

Please include information like:

* full output of the error you received
* what command you ran: `(in py-evm)$ pytest tests/json-fixtures/test_blockchain.py::test_blockchain_fixtures[.../py-evm/fixtures/BlockchainTests/GeneralStateTests/stCreate2/create2callPrecompiles_d5g0v0.json:create2callPrecompiles_d5g0v0_Constantinople:Constantinople] ` replace ... with your absolute path
* the code that caused the failure: `py_ecc.optimized_bn128.optimized_field_elements.FQ`

```                                                                                                                     

tests/json-fixtures/test_blockchain.py F                                                                                             [100%]

================================================================= FAILURES =================================================================
 test_blockchain_fixtures[py-evm/fixtures/BlockchainTests/GeneralStateTests/stCreate2/create2callPrecompiles_d5g0v0.json:create2callPrecompiles_d5g0v0_Constantinople:Constantinople] 

fixture_data = ('py-evm/fixtures/BlockchainTests/GeneralStateTests/stCreate2/create2callPrecompiles_d5g0v0.json', 'create2callPrecompiles_d5g0v0_Constantinople', 'Constantinople')
fixture = {'blocks': [{'blockHeader': {'bloom': 0, 'coinbase': b'*\xdc%fP\x18\xaa\x1f\xe0\xe6\xbcfm\xac\x8f\xc2i\x7f\xf9\xba', '... 'lastblockhash': b'\xd3\x92\r\x904,\x0f\t\xaex$f/\x964\xd7\x8d\x8d\xfb\xf95\xdfK\x0f\x04\n\x81\xa5\x0c\xa2g\x95', ...}

    def test_blockchain_fixtures(fixture_data, fixture):
        try:
            chain = new_chain_from_fixture(fixture)
        except ValueError as e:
            raise AssertionError("could not load chain for {}".format((fixture_data,))) from e
    
        genesis_params = genesis_params_from_fixture(fixture)
        expected_genesis_header = BlockHeader(**genesis_params)
    
        # TODO: find out if this is supposed to pass?
        # if 'genesisRLP' in fixture:
        #     assert rlp.encode(genesis_header) == fixture['genesisRLP']
    
        genesis_block = chain.get_canonical_block_by_number(0)
        genesis_header = genesis_block.header
    
        assert_imported_genesis_header_unchanged(expected_genesis_header, genesis_header)
    
        # 1 - mine the genesis block
        # 2 - loop over blocks:
        #     - apply transactions
        #     - mine block
        # 3 - diff resulting state with expected state
        # 4 - check that all previous blocks were valid
    
        mined_blocks = list()
        for block_fixture in fixture['blocks']:
            should_be_good_block = 'blockHeader' in block_fixture
    
            if 'rlp_error' in block_fixture:
                assert not should_be_good_block
                continue
    
            if should_be_good_block:
                (block, mined_block, block_rlp) = apply_fixture_block_to_chain(
                    block_fixture,
                    chain,
>                   perform_validation=False  # we manually validate below
                )

block_fixture = {'blockHeader': {'bloom': 0, 'coinbase': b'*\xdc%fP\x18\xaa\x1f\xe0\xe6\xbcfm\xac\x8f\xc2i\x7f\xf9\xba', 'difficulty':...x00a\x01\x00`\x00`\x00`\x06b\t'\xc0\xf1`\x02U`\x00Q`\x00U\x00", 'gasLimit': 15000000, 'gasPrice': 1, 'nonce': 0, ...}]}
chain      = <abc.ChainFromFixture object at 0x10d834278>
expected_genesis_header = <BlockHeader #0 8a27153c>
fixture    = {'blocks': [{'blockHeader': {'bloom': 0, 'coinbase': b'*\xdc%fP\x18\xaa\x1f\xe0\xe6\xbcfm\xac\x8f\xc2i\x7f\xf9\xba', '... 'lastblockhash': b'\xd3\x92\r\x904,\x0f\t\xaex$f/\x964\xd7\x8d\x8d\xfb\xf95\xdfK\x0f\x04\n\x81\xa5\x0c\xa2g\x95', ...}
fixture_data = ('py-evm/fixtures/BlockchainTests/GeneralStateTests/stCreate2/create2callPrecompiles_d5g0v0.json', 'create2callPrecompiles_d5g0v0_Constantinople', 'Constantinople')
genesis_block = <ConstantinopleBlock(#Block #0)>
genesis_header = <BlockHeader #0 8a27153c>
genesis_params = {'block_number': 0, 'bloom': 0, 'coinbase': b'*\xdc%fP\x18\xaa\x1f\xe0\xe6\xbcfm\xac\x8f\xc2i\x7f\xf9\xba', 'difficulty': 131072, ...}
mined_blocks = []
should_be_good_block = True

tests/json-fixtures/test_blockchain.py:269: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
eth/tools/fixtures/helpers.py:232: in apply_fixture_block_to_chain
    mined_block, _, _ = chain.import_block(block, perform_validation=perform_validation)
eth/chains/base.py:726: in import_block
    imported_block = self.get_vm(base_header_for_import).import_block(block)
eth/vm/base.py:539: in import_block
    new_header, receipts, _ = self.apply_all_transactions(block.transactions, self.block.header)
eth/vm/base.py:492: in apply_all_transactions
    transaction,
eth/vm/base.py:408: in apply_transaction
    state_root, computation = self.state.apply_transaction(transaction)
eth/vm/state.py:256: in apply_transaction
    computation = self.execute_transaction(transaction)
eth/vm/forks/frontier/state.py:201: in execute_transaction
    return executor(transaction)
eth/vm/state.py:307: in __call__
    computation = self.build_computation(message, valid_transaction)
eth/vm/forks/frontier/state.py:133: in build_computation
    transaction_context,
eth/vm/forks/spurious_dragon/computation.py:33: in apply_create_message
    computation = self.apply_message()
eth/vm/forks/frontier/computation.py:76: in apply_message
    self.transaction_context,
eth/vm/computation.py:583: in apply_computation
    opcode_fn(computation=computation)
eth/vm/logic/system.py:215: in __call__
    return super().__call__(computation)
eth/vm/logic/system.py:193: in __call__
    self.apply_create_message(computation, child_msg)
eth/vm/logic/system.py:252: in apply_create_message
    child_computation = computation.apply_child_computation(child_msg)
eth/vm/computation.py:395: in apply_child_computation
    child_computation = self.generate_child_computation(child_msg)
eth/vm/computation.py:404: in generate_child_computation
    self.transaction_context,
eth/vm/forks/spurious_dragon/computation.py:33: in apply_create_message
    computation = self.apply_message()
eth/vm/forks/frontier/computation.py:76: in apply_message
    self.transaction_context,
eth/vm/computation.py:583: in apply_computation
    opcode_fn(computation=computation)
eth/vm/logic/call.py:136: in __call__
    child_computation = computation.apply_child_computation(child_msg)
eth/vm/computation.py:395: in apply_child_computation
    child_computation = self.generate_child_computation(child_msg)
eth/vm/computation.py:410: in generate_child_computation
    self.transaction_context,
eth/vm/forks/frontier/computation.py:76: in apply_message
    self.transaction_context,
eth/vm/computation.py:569: in apply_computation
    computation.precompiles[message.code_address](computation)
eth/precompiles/ecadd.py:35: in ecadd
    result = _ecadd(computation.msg.data_as_bytes)
eth/precompiles/ecadd.py:59: in _ecadd
    p1 = validate_point(x1, y1)
eth/_utils/bn128.py:26: in validate_point
    if not bn128.is_on_curve(p1, bn128.b):
../py_ecc/py_ecc/optimized_bn128/optimized_curve.py:69: in is_on_curve
    return y**2 * z - x**3 == b * z**3
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = 3, other = 1

    def __mul__(self, other: IntOrFQ) -> "FQ":
        if isinstance(other, FQ):
            on = other.n
        elif isinstance(other, int):
            on = other
        else:
            raise TypeError(
                "Expected an int or FQ object, but got object of type {}"
>               .format(type(other))
            )
E           TypeError: Expected an int or FQ object, but got object of type <class 'py_ecc.optimized_bn128.optimized_field_elements.FQ'>

other      = 1
self       = 3

../py_ecc/py_ecc/fields/optimized_field_elements.py:67: TypeError
========================================================= 1 failed in 8.43 seconds =========================================================
```

### How can it be fixed

- might need a separate branch for the release

### PR DESCRIPTION
**Pull request by ChihChengLiang**
### What was wrong?

#59

### How was it fixed?

This makes py-evm tests happy

#### Cute Animal Picture

<a title="(c) Programa de Conservación Ex-situ del Lince Ibérico  www.lynxexsitu.es [CC BY 3.0 es (https://creativecommons.org/licenses/by/3.0/es/deed.en)], via Wikimedia Commons" href="https://commons.wikimedia.org/wiki/File:Linces1.jpg">Linces1</a>

### CODE REVIEW

**Comment by pipermerriam** [comment]
Seems :+1: but want to double check with @Bhargavasomu since he's more familiar with this (and since this is really sensitive code)

**Comment by Bhargavasomu** [comment]
@ChihChengLiang I actually don't want the `FQ` or `FQP` or `FQ2` or `FQ12` to be accessed from the `curve api`. I would ideally prefer the `FQ`, `FQP`, `FQ2`, `FQ12` to be accessed from the `fields API`. We should probably change the `code` and `tests` in `py-evm` instead of the `API`. I will now try to change the `code in the tests` of `py-evm` and will get back to you. Please let me know if you have other opinions or approaches.

/cc @pipermerriam

**Comment by carver** [comment]
> We should probably change the `code` and `tests` in `py-evm` instead of the `API`. I will now try to change the `code in the tests` of `py-evm` and will get back to you. Please let me know if you have other opinions or approaches.

We can't assume that `py-evm` is the only user of `py-ecc`. We must keep backwards compatibility.

**Comment by pipermerriam** [comment]
Also, the way forward is to document the APIs that are public so that when we do a major bump there's a clear distinction.  This can be as simple as an enumeration of the *public* APIs in the `README.md` for now, ideally with some code examples of how to use them.

**Comment by Bhargavasomu** [comment]
This is a duplicate of #56 and hence can be closed.

**Comment by ChihChengLiang** [comment]
closed in favor of #56

**Pull request closed without merging**
