### PR TITLE
Enable Type Hinting for optimized_bn128 module

### PR DESCRIPTION
**Pull request by Bhargavasomu**
### What was wrong?
As part of #11 , the module `optimized_bn128` needs to be type hinted

### How was it fixed?
Manually type hinting and running `mypy`.

#### Cute Animal Picture

put a cute animal picture link inside the parentheses

### CODE REVIEW

**Comment by Bhargavasomu** [comment]
@pipermerriam this is just for checking the correctness, and apparently there is a flake error in `bls` module as per the linting error. Should I be bothered about that?

Also I will be making the necessary changes as per #28

**Comment by Bhargavasomu** [comment]
@pipermerriam could you please take a look now?

**Comment by pipermerriam** [comment]
@Bhargavasomu I'm going to wait for #28 to be reviewed and merged and then this can be rebased (after which I'll take a look).

**Comment by Bhargavasomu** [comment]
@pipermerriam could you take a look at this and we can close the issue and bounty #11.

**Pull request merged**
